global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: node
  honor_timestamps: true
  honor_labels: true
  scrape_interval: 1s
  scrape_timeout: 1s
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - pushgateway:9091